server:
  port: 18085

spring:
  application:
    name: config-server
    #≈‰÷√git≤÷ø‚µÿ÷∑
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiangeric/config-demo-repository.git
